Dat210.PhotoManager/Dat210.PhotoManager.Web/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dat210.PhotoManager.Business;
using Dat210.PhotoManager.Contracts;
using Dat210.PhotoManager.Web.Models;

namespace Dat210.PhotoManager.Web.Controllers
{
    public class SystemController : BaseController
    {
        private readonly IIndexingService _service;
        private readonly IApplicationConfiguration _configuration;

        public SystemController(IIndexingService service, IApplicationConfiguration configuration)
        {
            _service = service;
            _configuration = configuration;
        }

        //
        // GET: /System/
        public ActionResult Index()
        {
            return View(new SystemViewModel
            {
                IndexingService = _service, 
                PhotoLibraryPath = _configuration.GetPhotoLibraryPath(), 
                ThumbnailPath = _configuration.GetThumbnailPath()
            });
        }

        public ActionResult SetPhotoLibraryPath(string photoLibraryPath)
        {
            _configuration.SetPhotoLibraryPath(photoLibraryPath);
            _service.Add();
            return RedirectToAction("Index");
        }

        public ActionResult SetThumbnailPath(string thumbnailPath)
        {
            _configuration.SetThumbnailPath(thumbnailPath);
            return RedirectToAction("Index");
        }
	}
}

Dat210.PhotoManager/Dat210.PhotoManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@{
               if (!String.IsNullOrEmpty(ViewBag.Title))
               {
                   @(ViewBag.Title + " – ")
               }
               @("Uis Photo Manager")
           }</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("UiS Photo Manager", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Bildegalleri", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Innstillinger", "Index", "System", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <div style="clear:both"></div>
        <hr />
        <footer style="text-align: center;">
            <p>&copy; @DateTime.Now.Year - Gruppe E – DAT210 Våren 2014 – Universitetet i Stavanger</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>